version: '3.8'
services:
  bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 
